"""empty message

Revision ID: 020b0f579944
Revises: 292724b830d2
Create Date: 2017-02-26 15:07:21.169092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020b0f579944'
down_revision = '292724b830d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_request', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_request', 'deleted')
    # ### end Alembic commands ###
