"""empty message

Revision ID: 2407bb52aee9
Revises: 85bba8d346c6
Create Date: 2017-04-17 13:20:27.016166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2407bb52aee9'
down_revision = '85bba8d346c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_mapping_table', sa.Column('device_profile_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'location_mapping_table_device_id_fkey', 'location_mapping_table', type_='foreignkey')
    op.create_foreign_key(None, 'location_mapping_table', 'device_profile', ['device_profile_id'], ['id'])
    op.drop_column('location_mapping_table', 'device_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location_mapping_table', sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'location_mapping_table', type_='foreignkey')
    op.create_foreign_key(u'location_mapping_table_device_id_fkey', 'location_mapping_table', 'device', ['device_id'], ['id'])
    op.drop_column('location_mapping_table', 'device_profile_id')
    # ### end Alembic commands ###
