"""empty message

Revision ID: 3da5327a39c8
Revises: a9cac143b56a
Create Date: 2017-04-17 23:23:05.880422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da5327a39c8'
down_revision = 'a9cac143b56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('layer7_value', sa.String(length=50), nullable=True))
    op.drop_column('service', 'layer4_value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('layer4_value', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('service', 'layer7_value')
    # ### end Alembic commands ###
