"""empty message

Revision ID: 48c92d99d6e1
Revises: 4a6eeb2fd34e
Create Date: 2017-04-04 16:34:33.248510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c92d99d6e1'
down_revision = '4a6eeb2fd34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_uc', 'location', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_uc', 'location', type_='unique')
    # ### end Alembic commands ###
