"""empty message

Revision ID: 697d905c6049
Revises: 020b0f579944
Create Date: 2017-02-26 15:23:07.870486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697d905c6049'
down_revision = '020b0f579944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_request', sa.Column('status', sa.Enum('open', 'closed', 'completed', name='stateoptions'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('change_request', 'status')
    # ### end Alembic commands ###
