"""empty message

Revision ID: 897a13e1f01e
Revises: 697d905c6049
Create Date: 2017-02-27 19:47:45.060562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897a13e1f01e'
down_revision = '697d905c6049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('apikey', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('driver', sa.Enum('juniper_srx', 'palo_alto_panorama', name='driveroptions'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'blacklist_token', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'deleted')
    op.drop_column(u'blacklist_token', 'deleted')
    op.drop_table('device')
    # ### end Alembic commands ###
