"""empty message

Revision ID: 9952be8bd469
Revises: 3da5327a39c8
Create Date: 2017-04-17 23:38:59.771620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9952be8bd469'
down_revision = '3da5327a39c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('change_request_destination_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('change_request_source_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'address_change_request_id_fkey', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'change_request', ['change_request_source_id'], ['id'])
    op.create_foreign_key(None, 'address', 'change_request', ['change_request_destination_id'], ['id'])
    op.drop_column('address', 'change_request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('change_request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key(u'address_change_request_id_fkey', 'address', 'change_request', ['change_request_id'], ['id'])
    op.drop_column('address', 'change_request_source_id')
    op.drop_column('address', 'change_request_destination_id')
    # ### end Alembic commands ###
