"""empty message

Revision ID: a9cac143b56a
Revises: bf3e7f5622c9
Create Date: 2017-04-17 23:11:48.530046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cac143b56a'
down_revision = 'bf3e7f5622c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('change_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'change_request', ['change_request_id'], ['id'])
    op.add_column('service', sa.Column('change_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service', 'change_request', ['change_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.drop_column('service', 'change_request_id')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'change_request_id')
    # ### end Alembic commands ###
